{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-registry-pull-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict .Values.imagePullSecrets.registry (dict "username" .Values.imagePullSecrets.username "password" .Values.imagePullSecrets.password)) | toJson | quote }}
{{- end }}
