{{- if .Values.flyway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.flyway.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database-migration
automountServiceAccountToken: false
{{- if .Values.imagePullSecrets.enabled }}
imagePullSecrets:
  - name: ghcr-registry-pull-secret
{{- end }}
{{- end }}
